# Generated by Django 5.1.4 on 2025-02-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="painting",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
