# Generated by Django 5.1.4 on 2025-02-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Painting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(upload_to="paintings/")),
                (
                    "medium",
                    models.CharField(
                        choices=[
                            ("Acrylic on Canvas", "Acrylic on Canvas"),
                            ("Oil Painting", "Oil Painting"),
                            ("Watercolor", "Watercolor"),
                            ("Pencil Sketch", "Pencil Sketch"),
                            ("Charcoal Drawing", "Charcoal Drawing"),
                            ("Mixed Media", "Mixed Media"),
                        ],
                        default="Acrylic on Canvas",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
